// Generated by CoffeeScript 1.10.0
(function() {
  var User, mongoose, settings;

  mongoose = require('mongoose');

  settings = require('../routes/settings');

  User = require('../model/User');

  exports.regesiter = function(req, res) {
    return User.userCheckedByPhone(req.body.phoneNumber, function(err, count) {
      if (err) {
        return res.json({
          success: false,
          err: err
        });
      } else {
        if (count === 0) {
          return User.userCount(function(err, userCount) {
            var login, newUser;
            if (err) {
              return res.redirect('user/login');
            } else {
              login = [
                {
                  time: new Date()
                }
              ];
              newUser = new User({
                userid: 1000 + count,
                username: req.body.phoneNumber,
                phoneNumber: req.body.phoneNumber,
                password: req.body.password,
                date: new Date(),
                login: login
              });
              return newUser.save(function(err) {
                if (err) {
                  return res.json({
                    success: false,
                    err: err
                  });
                } else {
                  console.log('emodoou_text:sucess');
                  return res.redirect('/user/login');
                }
              });
            }
          });
        } else {
          console.log("账号存在");
          return res.redirect('user/login');
        }
      }
    });
  };

  exports.login = function(req, res) {
    return User.login(req.body.phoneNumber, req.body.password, function(err, count, user) {
      if (err) {
        return res.redirect('/index');
      } else {
        if (count > 0) {
          req.session.user = user.user;
          req.session.userid = user.userid;
          return res.json({
            success: true
          });
        } else {
          return res.json({
            success: false
          });
        }
      }
    });
  };

}).call(this);
